name: Deploy Frontend (ReactJS) to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # ⏱ Dừng nếu quá 10 phút

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        env:
          CI: false

      - name: Build React app
        run: npm run build

      - name: Deploy build folder to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: tilab.com.vn
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/tilab-frontend/build"
          strip_components: 1
          timeout: 60s  # ép dừng sau 60s nếu lỗi treo

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: tilab.com.vn
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          script: |
            sudo systemctl reload nginx
